In [1]:
import numpy as np

a = np.zeros(3)

print(a)

[0. 0. 0.]


In [3]:
z=np.ones(10)
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
z = np.linspace(1,33,17)
# numpy ndarray object
print(type(z))
print(z[1])
print([z])

<class 'numpy.ndarray'>
3.0
[array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33.])]


In [27]:
z.shape
# get details with ?
?z.shape

Type:        tuple
String form: (17,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [28]:
# numpy has a random
np.random.seed(1)
z1 = np.random.randint(10, size=6)
z1

array([5, 8, 9, 5, 0, 0])

In [29]:
bv = [1,2, 3,4,5]
nbv = np.array(bv)
nbv[0:2]


array([1, 2])